services:
  surreal:
    image: "surrealdb/surrealdb:latest"
    container_name: surreal
    ports:
      - "8000:8000"
    volumes:
      - weather:/weather/db
    restart: unless-stopped
    command: start --auth file:/weather/db/db
    user: root
  nwws-go:
    build: "./parser/"
    restart: unless-stopped
    container_name: "nwws-go"
    volumes:
      - weather:/weather/nwws
    env_file:
      - .env
  nwws-oi:
    build: "./xmpp/"
    restart: unless-stopped
    container_name: nwws-oi
    volumes:
      - weather:/weather/nwws
    env_file:
      - .env
volumes:
  weather:
      name: weather
  